
clear
RESET='\033[0m'; BOLD='\033[1m'; ORANGE='\033[38;5;208m'; RED='\033[38;5;196m'
WHITE='\033[38;5;255m'; GRAY='\033[38;5;244m'; DARK='\033[38;5;236m'
GREEN='\033[38;5;46m'; CYAN='\033[38;5;51m'; YELLOW='\033[38;5;226m'; PURPLE='\033[38;5;135m'

echo ""
echo ""
echo -e "${ORANGE}${BOLD}  ████████████████████████████████████████████████████████████████████████${RESET}"
echo -e "${ORANGE}${BOLD}  █                                                                      █${RESET}"
echo -e "${ORANGE}${BOLD}  █   GOOGLE CLOUD RAPID AGENT HACKATHON 2026  ·  GitLab Partner Track  █${RESET}"
echo -e "${ORANGE}${BOLD}  █                                                                      █${RESET}"
echo -e "${ORANGE}${BOLD}  ████████████████████████████████████████████████████████████████████████${RESET}"
echo ""
echo -e "${WHITE}${BOLD}  ███████╗██╗  ██╗██╗███████╗████████╗██╗     ███████╗███████╗████████╗${RESET}"
echo -e "${WHITE}${BOLD}  ██╔════╝██║  ██║██║██╔════╝╚══██╔══╝██║     ██╔════╝██╔════╝╚══██╔══╝${RESET}"
echo -e "${WHITE}${BOLD}  ███████╗███████║██║█████╗     ██║   ██║     █████╗  █████╗     ██║   ${RESET}"
echo -e "${ORANGE}${BOLD}  ╚════██║██╔══██║██║██╔══╝     ██║   ██║     ██╔══╝  ██╔══╝     ██║   ${RESET}"
echo -e "${ORANGE}${BOLD}  ███████║██║  ██║██║██║        ██║   ███████╗███████╗██║        ██║   ${RESET}"
echo -e "${ORANGE}${BOLD}  ╚══════╝╚═╝  ╚═╝╚═╝╚═╝        ╚═╝   ╚══════╝╚══════╝╚═╝        ╚═╝   ${RESET}"
echo ""
echo -e "${WHITE}${BOLD}               Autonomous Bug-Fixing Agent for GitLab${RESET}"
echo ""
echo -e "    ${GRAY}┌──────────────┐${RESET}         ${GRAY}┌──────────────┐${RESET}"
echo -e "    ${CYAN}${BOLD}│  GitLab Issue │${RESET}  ${ORANGE}──▶${RESET}  ${GREEN}${BOLD}│ Merge Request│${RESET}"
echo -e "    ${GRAY}│  (labeled)   │${RESET}         ${GRAY}│  (auto-fix)  │${RESET}"
echo -e "    ${GRAY}└──────────────┘${RESET}         ${GRAY}└──────────────┘${RESET}"
echo ""
echo -e "                       ${YELLOW}${BOLD}⏱  58 seconds. No human code.${RESET}"
echo ""
echo -e "  ${DARK}  ──────────────────────────────────────────────────────────────────${RESET}"
echo ""
echo -e "  ${BOLD}   Pipeline :${RESET}  ${CYAN}Cartographer${RESET}  ${GRAY}▶${RESET}  ${PURPLE}Triage${RESET}  ${GRAY}▶${RESET}  ${CYAN}Coder${RESET}  ${GRAY}▶${RESET}  ${GREEN}Auditor${RESET}  ${GRAY}▶${RESET}  ${ORANGE}HITL${RESET}"
echo ""
echo -e "  ${BOLD}   LLM      :${RESET}  ${CYAN}Gemini 2.0 Flash on ${ORANGE}Vertex AI${RESET}${CYAN} (Google Cloud)${RESET}"
echo -e "  ${BOLD}   Orch     :${RESET}  ${PURPLE}LangGraph${RESET}  ${GRAY}—${RESET}  5-agent cyclic state machine"
echo -e "  ${BOLD}   GitLab   :${RESET}  ${ORANGE}MCP${RESET}  ${GRAY}+${RESET}  REST API  ${GRAY}—${RESET}  branch · commit · MR"
echo -e "  ${BOLD}   Observe  :${RESET}  ${PURPLE}Arize Phoenix${RESET}  ${GRAY}—${RESET}  all LLM calls traced"
echo ""
echo -e "  ${DARK}  ──────────────────────────────────────────────────────────────────${RESET}"
echo ""
echo -e "  ${BOLD}${GREEN}  100%${RESET}${GRAY} triage accuracy${RESET}    ${BOLD}${GREEN}100%${RESET}${GRAY} MR success${RESET}    ${BOLD}${YELLOW}  57s${RESET}${GRAY} avg to MR${RESET}    ${BOLD}${CYAN}<\$0.01${RESET}${GRAY} / run${RESET}"
echo ""
echo -e "${ORANGE}${BOLD}  ████████████████████████████████████████████████████████████████████████${RESET}"
echo -e "${ORANGE}${BOLD}  █                                                                      █${RESET}"
echo -e "${ORANGE}${BOLD}  █    github.com/amareshhebbar/ShiftLeft   ·   shiftleft.streamlit.app  █${RESET}"
echo -e "${ORANGE}${BOLD}  █                                                                      █${RESET}"
echo -e "${ORANGE}${BOLD}  ████████████████████████████████████████████████████████████████████████${RESET}"
echo ""
echo ""
