"""
HITL (Human-in-the-Loop) agent — the final node.

Creates a GitHub branch, commits all patches and .shiftleft/ YAMLs,
opens a Pull Request, fetches the per-file diffs, and records an audit log.
The human then reviews the PR via the Streamlit UI or directly on GitHub.
"""

import yaml
import tempfile
import os
from datetime import datetime, timezone

from core.state import ShiftLeftState
from tools.github_tools import (
    create_branch,
    commit_files,
    open_pr,
    get_pr_diff,
)
from utils.config import GITHUB_TARGET_REPO, DEFAULT_BASE_BRANCH
from utils.logger import get_logger

log = get_logger(__name__)


def _pr_body(state: ShiftLeftState, changed_files: list) -> str:
    file_list = "\n".join(f"- `{f}`" for f in changed_files) or "_(none)_"
    tests     = state.get("test_results", {})
    status    = "✅ Passed" if state.get("tests_passed") else "⚠️ Failed / max retries"
    return f"""## ShiftLeft automated patch

| Field | Value |
|---|---|
| Run ID | `{state['run_id']}` |
| Trigger | {state.get('trigger_source', 'unknown')} |
| Severity | {state.get('severity', 'unknown')} |
| Test status | {status} |
| Test duration | {tests.get('duration', 0)}s |

### Issue summary
{state.get('issue_summary', 'N/A')}

### Files changed
{file_list}

### How to review
1. Use the **Files changed** tab to inspect diffs.
2. Click **Review in VS Code** in the ShiftLeft dashboard for the full merge editor.
3. Accept or reject individual files from the ShiftLeft review page.

---
*Generated by [ShiftLeft](https://github.com/yourname/shiftleft) — do not edit manually.*
"""


def hitl_node(state: ShiftLeftState) -> ShiftLeftState:
    repo   = GITHUB_TARGET_REPO
    branch = state["branch_name"]
    run_id = state["run_id"]

    log.info(f"[hitl] creating branch {branch}")
    create_branch(repo, branch, DEFAULT_BASE_BRANCH)

    # ── collect all files to commit ────────────────────────────────────────
    files_to_commit: dict[str, str] = {}

    patches = state.get("patches") or []
    changed_files = []
    for patch in patches:
        files_to_commit[patch["filename"]] = patch["content"]
        changed_files.append(patch["filename"])

    yaml_map = state.get("yaml_map") or {}
    files_to_commit.update(yaml_map)

    if not files_to_commit:
        log.warning("[hitl] nothing to commit")
        return {**state, "pr_url": None, "diff_hunks": {}}

    log.info(f"[hitl] committing {len(files_to_commit)} files")
    commit_files(
        repo, branch, files_to_commit,
        message=f"chore(shiftleft): automated run {run_id}",
    )

    # ── open PR ────────────────────────────────────────────────────────────
    summary   = (state.get("issue_summary") or run_id)[:72]
    pr_info   = open_pr(
        repo_name=repo,
        branch=branch,
        title=f"ShiftLeft: {summary}",
        body=_pr_body(state, changed_files),
    )

    # ── fetch diffs for Streamlit review UI ───────────────────────────────
    diff_hunks = get_pr_diff(repo, pr_info["pr_number"])

    # ── commit audit YAML ─────────────────────────────────────────────────
    audit_content = yaml.dump({
        "run_id":        run_id,
        "timestamp":     datetime.now(timezone.utc).isoformat(),
        "trigger":       state.get("trigger_source", "unknown"),
        "issue_summary": state.get("issue_summary", ""),
        "severity":      state.get("severity", "unknown"),
        "files_changed": changed_files,
        "tests_passed":  state.get("tests_passed", False),
        "test_output":   state.get("test_results", {}).get("output", ""),
        "pr_url":        pr_info["pr_url"],
        "pr_number":     pr_info["pr_number"],
        "iterations":    state.get("iteration", 1),
    }, default_flow_style=False)

    commit_files(
        repo, branch,
        {f".shiftleft/audits/{run_id}.yaml": audit_content},
        message=f"chore(shiftleft): audit log {run_id}",
    )

    log.info(f"[hitl] done — PR: {pr_info['pr_url']}")
    return {
        **state,
        "pr_url":       pr_info["pr_url"],
        "pr_number":    pr_info["pr_number"],
        "diff_hunks":   diff_hunks,
        "changed_files": changed_files,
    }